### ISSUE TITLE
A problem occurred starting process 'command 'hg''

### ISSUE THREAD

**Issue by medexdev** [nviennot/jd-core-java#20]
I'm getting this exception when i run ./gradlew assemble. I try it in windows, cygwin and unix. All give the same exception.

[root@XXX jd-core-java-master]# ./gradlew assemble
:compileJava
Note: /home/jd-core-java-master/src/main/java/com/intellij/openapi/application/Application.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:processResources UP-TO-DATE
:classes
:getNativeLibs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':getNativeLibs'.
> A problem occurred starting process 'command 'hg''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.599 secs

**Comment by nviennot** [comment]
Install hg (mercury)

**Comment by soumali** [comment]
Process 'command 'hg'' finished with non-zero exit value 255

gradlew.bat assemble

:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:getNativeLibs
abort: error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
:getNativeLibs FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':getNativeLibs'.

Process 'command 'hg'' finished with non-zero exit value 255
Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED

Total time: 1 mins 13.079 secs
