### ISSUE TITLE
Native library not found 

### ISSUE THREAD

**Issue by simjeet** [nviennot/jd-core-java#22]
native libraries i.e. .dll files were not found on the bitbucket repository of intellije. 
 I also ran the build. The jar was created successfully but when i tried to execute the jar it was throwing exception of native libraries not found.

**Comment by yolapop** [comment]
Having this issue too...

**Comment by k06a** [comment]
@nviennot having same error!

**Comment by k06a** [comment]
So all you need @simjeet and @yolapop is to fix 1 line in `build.gradle`:
```
commandLine 'hg', 'clone', JD_INTELLIJ_REPO_URL
```
=>
```
commandLine 'hg', 'clone', JD_INTELLIJ_REPO_URL, '-r', 'version-0.6'
```

and then run `./gradlew assemble`

**Comment by nviennot** [comment]
Thanks @k06a !

**Comment by k06a** [comment]
@nviennot thanks for sharing `jd-core-java`!

**Comment by soumali** [comment]
Process 'command 'hg'' finished with non-zero exit value 255

gradlew.bat assemble

:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:getNativeLibs
abort: error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
:getNativeLibs FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':getNativeLibs'.

Process 'command 'hg'' finished with non-zero exit value 255
Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
